server:
  retention: 1h

  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  nodeSelector:
    kubernetes.io/os: ${operating_system}

  persistentVolume:
    accessModes:
      - ReadWriteOnce
    enabled: true
    mountPath: /data
    size: 20Gi
    storageClass: gp2

alertmanager:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

pushgateway:
  nodeSelector:
    kubernetes.io/os: ${operating_system}

nodeExporter:
  nodeSelector:
    kubernetes.io/os: ${operating_system}
