apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
spec:
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName:  efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0ba8e37dd4304d2c0::fsap-0746c8cb42ee19db1 #Replace with your EFS id and EFS mount point ID
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-alertmanager
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  efs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName:  efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0ba8e37dd4304d2c0::fsap-0fd7a7dc22135d46f #Replace values with your EDS id and your EFS access Point ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  efs-sc
  resources:
    requests:
      storage: 10Gi